package com.tgtg.restaurant.domain.importer.domain

case class Restaurant(
                     name:String,
                     address:String,
                     unit:String,
                     zipCode:String,
                     city:String,
                     telephone:String,
                     email:String,
                     category:String,
                     cost:String,
                     onlineOrder:String,
                     takeaway:String,
                     diveIn:String,
                     dineIn:String,
                     offerings1:String,
                     offerings2:String,
                     offerings3:String,
                     offerings4:String,
                     offerings5:String,
                     diningOption1:String,
                     diningOption2:String,
                     diningOption3:String,
                     diningOption4:String,
                     diningOption5:String,
                     diningOption6:String,
                     diningOption7:String,
                     website:String,
                     longitude:String,
                     lattitude:String
                     )
